### ISSUE TITLE
Document lib_dirs

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc.ws#221]
The `lib_dirs` configuration attribute is not documented. It should be!

Context:

```
## 3.7 (2014-06-08)

[snip]
* Make lib dirs configurable using `lib_dirs` config attribute (#424) [Gregory Pakosz]
```

* https://github.com/nanoc/nanoc/issues/1337

**Comment by zor-el** [comment]
May I suggest in addition that the generated nanoc.yml should also contain the lib_dirs setting, at least in a commented form?

Here's what I've added to my nanoc.yml template:

``` yaml
# @since 3.7
# Code in lib_dirs is loaded in the sequence as they are listed. Monkey-patching rules apply.
# This is [lib] by default but can be changed to include helpers located elsewhere, like so:
# lib_dirs: [lib, other/lib]
```

**Comment by ddfreyne** [comment]
Fixed in 587cae490d73f42607cc7a978bed6316ccb32e1f.

@zor-el The most recent version of Nanoc creates sites with a much more minimal `nanoc.yaml` — not all configuration options are in there anymore, because many of them might never have to be changed.

I’m unsure of the benefits of adding version indicators to code and documentation. Some concerns:

* Does this replace the [release notes](https://nanoc.ws/release-notes/), which describe the new features in detail?

* Every feature is introduced in a certain version — at which point do we remove these version tags? After a year? After two minor versions? Keep all ones within the same major version (4.x)? Never?

* Nanoc is backwards-compatible within the same major version. Does it make sense to explicitly document which features are available in which versions, given that it’s easy to upgrade?

(Note that a new major version with breaking changes will need some versioning information — at that point, I’d probably split the site in a 4.x and 5.x section. But 5.x is probably very far off, still.)

**Comment by zor-el** [comment]
@ddfreyne, about the minimal `nanoc.yml`: I personally found it more helpful to have the settings listed in the generated config file than to wade through the documentation, especially when I started out with nanoc. Plus documentation is always lagging behind code, as we've just seen. ;-)

So having the options generated would be my preference, but that's just me. I do use my own scaffolding that's closer to my own needs, and my nanoc.yml template does have the settings listed in it. I keep adding settings as I discover them, like that `lib_dirs` option.

Hence the benefit of version tags, in case I'm tied to a legacy version. (Yes, backward compatibility is a nice thing, but then bugs happen, too, and waiting for a fix is not always a luxury one has.)

Again, this is just my process. No imposition intended.

BTW, I'm *absolutely delighted* by Nanoc. I've run into dead ends with other website generators, but never with Nanoc! 👍 👍 👍

**Comment by zor-el** [comment]
@ddfreyne, in retrospect, I feel I want to give a more thorough response to your comment.

> Does this replace the release notes, which describe the new features in detail?

IMO release notes are a notoriously wrong place for detailed documentation. Release notes are deltas, and while deltas are the easiest to write new information, the discoverability of that information is poor, especially when they are spread across multiple files. We just saw that `lib_dir´ was mentioned in a (rather old) release notes document, but never made it into the docs. On the other hand, a _What's New_ information is definitely useful as well. Ideally it would be possible to generate one from the other (or both from a common information base). Sadly, documentation that aspires to be good by human standards is stubbornly resistant to automation, in my experience.

> Every feature is introduced in a certain version — at which point do we remove these version tags? After a year? After two minor versions? Keep all ones within the same major version (4.x)? Never?

Never. As long as the feature exists, there is no point in removing the information. I personally tend to interpret that information in conjunction with stability. The older a feature is, the more stable and reliable I would assume it is. (Obviously this is not an absolute rule, but still.)

> Nanoc is backwards-compatible within the same major version. Does it make sense to explicitly document which features are available in which versions, given that it’s easy to upgrade?

Imagine a project where you _use_ Nanoc, and something that worked with 3.6 got broken in 3.7, fixed in 3.9, but a 3rd party dependency is locking you to <= 3.8. Or imagine the issue manifests in the interaction of more than one gem, so it's unclear what's causing it in the 1st place. Meanwhile, your project deadlines are getting closer and closer... I think you're getting the picture. :)

If you think this is a topic worth discussing further, and you'd like to take it to the [discussion group](https://groups.google.com/forum/#!newtopic/nanoc), I'd gladly join in.

**Comment by ddfreyne** [comment]
> about the minimal nanoc.yml: I personally found it more helpful to have the settings listed in the generated config file than to wade through the documentation, especially when I started out with Nanoc.

I’ll think about how I can make `nanoc.yaml` easier to use. I like a minimal configuration file, but I also understand your concern of not having all configuration options in there by default.

> Plus documentation is always lagging behind code, as we've just seen. ;-)

Not _always_ — but it’s tough to prevent!

> IMO release notes are a notoriously wrong place for detailed documentation.

Changes to Nanoc are described in two places at the moment:

* [“Release notes”](https://nanoc.ws/release-notes/)
* [“Detailed release notes”](https://nanoc.ws/release-notes/details/)

I think it makes sense to rename the former to _What’s new_ and the latter to _Release notes_. Do you agree?

> We just saw that `lib_dir´ was mentioned in a (rather old) release notes document, but never made it into the docs.

Mind you that `lib_dir` was added four years ago, and Nanoc’s release process has changed quite a bit since then. I don’t know how `lib_dir` escaped being documented, but I believe that it’s less likely to happen now, because of the _What’s new_ section (which is called _Release notes_ on the web site).

> Sadly, documentation that aspires to be good by human standards is stubbornly resistant to automation, in my experience.

Agreed!

Parts of the Nanoc web site used to be extracted from the Nanoc source code, but that led to two problems:

* Updating the documentation means releasing a new version of Nanoc.
* It’s really hard to write good documentation in source code.

Most of the documentation that lived in the source code (e.g. docs for filters and helpers) now live in the site again. It’s a trade-off…

One idea that I’ve been toying with is to move the documentation out of the `nanoc.ws` repository and into the `nanoc` repository. This way, changes will affect both the code *and* the documentation. The  `nanoc.ws` repository would then only contain the layout and infrastructure that is necessary in order to build the site.

Another idea would be to move the contents of the `nanoc.ws` repository into the `nanoc` repository entirely, but that’s likely quite a bit more tricky!

> As long as the feature exists, there is no point in removing the information. I personally tend to interpret that information in conjunction with stability. The older a feature is, the more stable and reliable I would assume it is. (Obviously this is not an absolute rule, but still.)

I’ll have to play around with a mechanism for adding version annotations to documentation. Do you have any examples of documentation that does this well?

>> Nanoc is backwards-compatible within the same major version. Does it make sense to explicitly document which features are available in which versions, given that it’s easy to upgrade?
>
> Imagine something that worked with 3.6 got broken in 3.7, fixed in 3.9, but a 3rd party dependency is locking you to <= 3.8. Or imagine the issue manifests in the interaction of more than one gem, so it's unclear what's causing it in the 1st place. Meanwhile, your project deadlines are getting closer and closer...

Makes sense. I wasn’t thinking about dependencies!

**Comment by ddfreyne** [comment]
> I think it makes sense to rename the former to _What’s new_ and the latter to _Release notes_. Do you agree?

I made this change; I think it looks better.

(I also realised that I’m rather derailing the discussion of the original issue at hand, but I like the conversation, so yeah.)

**Comment by zor-el** [comment]
@ddfreyne, I like the What's New name.

I also fully support keeping code and it's documentation in the same repository (or in dependant repositories, like it is possible with Mercurial), so that the same life cycle applies.

I think using the .ws repo just for layouts and site code (`lib_dirs´, mind you :)) and pulling content from the other repo is definitely the right way to go. In fact, I've been mentally playing with various scenarios myself how to organize code documentation and use Nanoc to generate a website around it. I think generating human-quality documentation while at the same minimizing information redundancy is both an exciting and a challenging topic worth a lively conversation.

In order not to derail the discussion of the original issue further... How about we take this conversation elsewhere? (Or not; I don't mind posting here, but re the original issue this is pretty much white noise.)

On a side note: I noticed we live in the same city, so we could even combine the conversation with a beer (and call it a meetup) 😀

**Comment by ddfreyne** [comment]
> In order not to derail the discussion of the original issue further.

I think the conversation is still mostly on-topic; after all, the original issue was that `lib_dirs` is undocumented, and the conversation that came out of it was about how to make sure that doesn’t happen again.

> I also fully support keeping code and it's documentation in the same repository

Then this definitely requires some experimentation!

> On a side note: I noticed we live in the same city, so we could even combine the conversation with a beer (and call it a meetup)

I’d certainly be up for that! I’ll be at [RUG::B](http://berlin.onruby.de/) next week, in case you’re interested.

**Comment by zor-el** [comment]
> I’ll be at RUG::B next week, in case you’re interested.

I'm afraid I won't be able to make it on time for the start. I might drop in later though, if that's okay.

**Comment by ddfreyne** [comment]
`lib_dirs` is documented.
