### ISSUE TITLE
Page not found - needs a redirect?

### ISSUE THREAD

**Issue by DaveEveritt** [nanoc/nanoc.ws#245]
in [this post on Stack Overflow](https://stackoverflow.com/q/20367811/123033), the following page is referenced:

https://nanoc.ws/docs/basics/

but /basics/ is a 404.

**Comment by ddfreyne** [comment]
Hmm, the redirects for nanoc.ws are gone since I switched to Netlify (an oversight on my part), though a redirect wouldn’t solve the particular problem for that Stack Overflow post, since even the fragment (`#as-partials`) is different.

I’ve updated the Stack Overflow post for now, which is a small step in the right direction.

I’ll look into setting up redirects again.

**Comment by ddfreyne** [comment]
Redirecting is a bit tricky, because there’s no clear location to redirect to! I’ll leave it as-is for now.

**Comment by DaveEveritt** [comment]
If the link on SO is changed, it's no longer a problem. Although, if it's worth doing, the best place for a redirect might be: https://nanoc.ws/doc/tutorial/
