### ISSUE TITLE
Cache fingerprinting doesn't take account of change to non-partial

### ISSUE THREAD

**Issue by iay** [nanoc/nanoc.ws#251]
I've been looking doing some significant style work on [my own Nanoc-based site](https://iay.org.uk/) and felt it would be useful to implement cache-busting if the stylesheet was going to change often. I came across first your Gist and then the code in this repository, which seems more or less the same.

It seems to me that the approach you use of composing the fingerprint from just the partials is strictly speaking insufficient as the fingerprint won't change if the non-partial (e.g., `print.scss`, `screen.scss`) is the thing that changes.

If the non-partial never changes, that's obviously not a problem and you'd probably never see an issue with your `screen.scss` which is just composed of a series of `@import`s. If you added another `@import` to the list, though, the fingerprint would stay the same, which isn't what I'd think you want.

`print.scss` contains actual CSS rules, though, and they are entirely unprotected by the fingerprint as I understand what you're doing.

So, am I missing something here, or would it be better to fingerprint all the `.scss` files, including the non-partials?

**Comment by iay** [comment]
The other option I thought might be interesting would be to hash the _compiled_ non-partial to figure out where it should live. That way, it would take into account any and all CSS in both the non-partial and in any partials it included, but nothing else (including, for example, `//` comments which aren't rendered to CSS. Is that possible, or do things happen in the wrong order for this to work?

**Comment by ddfreyne** [comment]
Hey @iay,

You’re absolutely correct — the fingerprint rule is not quite right. I will change it to `fingerprint('/assets/style/*')` (i.e. take all items into account), which is not _quite_ ideal as changing the screen stylesheet would also invalidates the print stylesheet, but the impact is so low that I’m just fine with it.

> The other option I thought might be interesting would be to hash the compiled non-partial to figure out where it should live.

This is not currently possible with Nanoc, because Nanoc needs to know where to write a file to before it is compiled. There are not many cases where this feels limiting, but fingerprinting is exactly one of them.

This is probably one of the topics that I’d tackle in a future version of Nanoc, though that is rather far in the future.

**Comment by ddfreyne** [comment]
Fixed in fe52d0a300c7a17cf146b12444e432731c9e631d.
